swagger: '2.0'
info:
  description: |
    ALPS平台示例，主要展示平台特性，以及打包部署流程
  version: "1.0.0"
  title: ALPS平台示例 API
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: console#http
    description: REST API接口演示模块
  - name: rss#ws
    description: Websocket接口演示模块
  - name: backend#msg
    description: 消息处理演示模块
paths:
  /user/verification-code:
    get:
      tags:
        - console#http
      summary: 获取登录验证码
      operationId: GetVerificationCodeInfo
      produces:
        - application/file
      responses:
        '200': #必须标记成字符串,加单引号
          description: 成功，返回二进制图片信息
          schema:
            type: string
            format: binary

  /user/login:
    post:
      tags:
        - console#http
      summary: 用户登录
      operationId: Login
      parameters:
        - name: request
          in: body
          description: request
          required: true
          schema:
            $ref: '#/definitions/LoginRequestInfo'
      responses:
        '200':
          description: 成功
          schema:
            $ref: '#/definitions/LoginResponseInfo'
          headers:
            x-auth-token:
              description: JWT
              type: string

  /user/logout/{user_id}:
    get:
      tags:
        - console#http
      summary: 用户注销登录
      operationId: Logout
      parameters:
        - name: x-access-token
          in: header
          description: JWT
          required: true
          type: string
        - name: user_id
          in: path
          description: 用户ID
          required: true
          type: string
      responses:
        200:
          description: 成功

  /user/headimage/{user_id}:
    post:
      tags:
        - console#http
      summary: 提交用户头像
      operationId: UploadUserHeadImageInfo
      consumes:
        - application/file
      parameters:
        - name: x-access-token
          in: header
          description: JWT
          required: true
          type: string
        - name: user_id
          in: path
          description: 用户ID
          required: true
          type: string
        - name: file
          in: body
          description: request
          required: true
          schema:
            type: string
            format: binary
      responses:
        '200':
          description: 成功

  '100': #ws、msg类型url需要加引号
    post:
      tags:
        - rss#ws
      summary: 添加用户订阅
      operationId: AddUserRssInfo
      parameters:
        - name: request
          in: body
          description: request
          required: true
          schema:
            $ref: '#/definitions/AddUserRssInfoRequestInfo'
      responses:
        '200':
          description: 成功
          schema:
            $ref: '#/definitions/AddUserRssInfoResponseInfo'

  'normal_msg/200':
    get:
      tags:
        - backend#msg
      summary: 处理一般消息
      operationId: DealUserMsgInfo
      parameters:
        - name: request
          in: body
          description: request
          required: true
          schema:
            $ref: '#/definitions/UserMsgInfoRequestInfo'
  'order_msg/201':
    post:
      tags:
        - backend#msg
      summary: 处理顺序消息
      operationId: DealUserOrderMsgInfo
      parameters:
        - name: request
          in: body
          description: request
          required: true
          schema:
            $ref: '#/definitions/UserMsgInfoRequestInfo'
  'broadcast_msg/202':
    put:
      tags:
        - backend#msg
      summary: 处理广播消息
      operationId: DealUserBroadcastMsgInfo
      parameters:
        - name: request
          in: body
          description: request
          required: true
          schema:
            $ref: '#/definitions/UserMsgInfoRequestInfo'

definitions:
  LoginRequestInfo:
    type: object
    properties:
      account:
        type: string
        description: 账户
      key:
        type: string
        description: 密码md5
      device_id:
        type: string
        description: 设备ID
      verification_code:
        type: string
        description: 验证码

  LoginResponseInfo:
    type: object
    properties:
      account:
        type: string
        description: 账户
      user_id:
        type: string
        description: 用户ID
      name:
        type: string
        description: 昵称
      head_image:
        type: string
        description: 头像ID
      register_time:
        type: integer
        format: int64
        description: 注册时间

  AddUserRssInfoRequestInfo:
    type: object
    properties:
      user_id:
        type: string
        description: 用户ID
      type:
        type: string
        description: 订阅类型
      token:
        type: string
        description: 用户TOKEN

  AddUserRssInfoResponseInfo:
    type: object
    properties:
      status:
        type: string
        description: 状态

  UserMsgInfoRequestInfo:
    type: object
    properties:
      user_id:
        type: string
        description: 用户ID